version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    volumes:
      - ./frontend:/usr/share/nginx/html  # Mount the frontend directory for live updates
